version: 2
jobs:
  check_version:
    docker:
      - image: python:3.7

    steps:
      - checkout

      - run:
          name: Check version number has been properly updated
          command: |
            git fetch
            .circleci/is-version-number-acceptable.sh

  install:
    docker:
      - image: python:3.7

    steps:
      - checkout

      - restore_cache:
          key: v1-py3-{{ .Branch }}-{{ checksum "setup.py" }}

      - run:
          name: Create a virtualenv
          command: |
            mkdir -p /tmp/venv/openfisca_core
            python -m venv /tmp/venv/openfisca_core
            echo "source /tmp/venv/openfisca_core/bin/activate" >> $BASH_ENV

      - run:
          name: Install dependencies
          command: |
            make install
            # pip install --editable git+https://github.com/openfisca/country-template.git@BRANCH_NAME#egg=OpenFisca-Country-Template  # use a specific branch of OpenFisca-Country-Template
            # pip install --editable git+https://github.com/openfisca/extension-template.git@BRANCH_NAME#egg=OpenFisca-Extension-Template  # use a specific branch of OpenFisca-Extension-Template

      - run:
          name: Delete compiled python files
          command: make clean

      - run:
          name: Compile python files to check for syntax errors
          command: make check-syntax-errors

      - save_cache:
          key: v1-py3-{{ .Branch }}-{{ checksum "setup.py" }}
          paths:
            - /tmp/venv/openfisca_core

  lint_style:
    docker:
      - image: python:3.7

    steps:
      - checkout

      - restore_cache:
          key: v1-py3-{{ .Branch }}-{{ checksum "setup.py" }}

      - run:
          name: Activate virtualenv
          command: echo "source /tmp/venv/openfisca_core/bin/activate" >> $BASH_ENV

      - run:
          name: Lint style
          command: make lint-style

  lint_types:
    docker:
      - image: python:3.7

    steps:
      - checkout

      - restore_cache:
          key: v1-py3-{{ .Branch }}-{{ checksum "setup.py" }}

      - run:
          name: Activate virtualenv
          command: echo "source /tmp/venv/openfisca_core/bin/activate" >> $BASH_ENV

      - run:
          name: Lint types
          command: make lint-types

      - run:
          name: Lint NumPy typing against latest 3 minor versions
          command: for i in {1..3}; do VERSION=$(.circleci/get-numpy-version.py prev) && pip install numpy==$VERSION && make lint-types; done

  test_code:
    docker:
      - image: python:3.7

    steps:
      - checkout

      - restore_cache:
          key: v1-py3-{{ .Branch }}-{{ checksum "setup.py" }}

      - run:
          name: Activate virtualenv
          command: echo "source /tmp/venv/openfisca_core/bin/activate" >> $BASH_ENV

      - run:
          name: Run core & web-api tests
          command: |
            pip install --editable . --upgrade --no-dependencies
            PYTEST_ADDOPTS="--exitfirst" make test-code

      - persist_to_workspace:
          root: .
          paths:
            - .coverage

      - run:
          name: Run country template tests
          command: |
            COUNTRY_TEMPLATE_PATH=`python -c "import openfisca_country_template; print(openfisca_country_template.CountryTaxBenefitSystem().get_package_metadata()['location'])"`
            openfisca test $COUNTRY_TEMPLATE_PATH/openfisca_country_template/tests/

  test_docs:
    docker:
      - image: python:3.7

    steps:
      - checkout

      - run:
          name: Checkout docs
          command: make test-doc-checkout branch=$CIRCLE_BRANCH

      - restore_cache:
          key: v1-py3-{{ .Branch }}-{{ checksum "setup.py" }}

      - restore_cache:
          key: v1-py3-docs-{{ .Branch }}-{{ checksum "doc/requirements.txt" }}

      - run:
          name: Create a virtualenv
          command: |
            mkdir -p /tmp/venv/openfisca_doc
            python -m venv /tmp/venv/openfisca_doc
            echo "source /tmp/venv/openfisca_doc/bin/activate" >> $BASH_ENV

      - run:
          name: Install dependencies
          command: make test-doc-install

      - save_cache:
          key: v1-py3-docs-{{ .Branch }}-{{ checksum "doc/requirements.txt" }}
          paths:
            - /tmp/venv/openfisca_doc

      - run:
          name: Run doc tests
          command: make test-doc-build

  submit_coverage:
    docker:
      - image: python:3.7

    steps:
      - checkout

      - attach_workspace:
          at: .

      - restore_cache:
          key: v1-py3-{{ .Branch }}-{{ checksum "setup.py" }}

      - run:
          name: Activate virtualenv
          command: echo "source /tmp/venv/openfisca_core/bin/activate" >> $BASH_ENV

      - run:
          name: Submit coverage to Coveralls
          command: |
            pip install coveralls
            coveralls

      - save_cache:
          key: v1-py3-{{ .Branch }}-{{ checksum "setup.py" }}
          paths:
            - /tmp/venv/openfisca_core

  deploy:
    docker:
      - image: python:3.7

    environment:
      PYPI_USERNAME: openfisca-bot
      # PYPI_PASSWORD: this value is set in CircleCI's web interface; do not set it here, it is a secret!

    steps:
      - checkout

      - restore_cache:
          key: v1-py3-{{ .Branch }}-{{ checksum "setup.py" }}

      - run:
          name: Activate virtualenv
          command: echo "source /tmp/venv/openfisca_core/bin/activate" >> $BASH_ENV

      - run:
          name: Check for functional changes
          command: if ! .circleci/has-functional-changes.sh ; then circleci step halt ; fi

      - run:
          name: Upload a Python package to Pypi
          command: .circleci/publish-python-package.sh

      - run:
          name: Publish a git tag
          command: .circleci/publish-git-tag.sh

      - run:
          name: Update doc
          command: |
            curl -X POST --header "Content-Type: application/json" -d '{"branch":"master"}' https://circleci.com/api/v1.1/project/github/openfisca/openfisca-doc/build?circle-token=$CIRCLE_TOKEN

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - check_version
      - install
      - lint_style:
          requires:
            - install
      - lint_types:
          requires:
            - install
      - test_code:
          requires:
            - install
      - test_docs:
          requires:
            - install
      - submit_coverage:
          requires:
            - test_code
      - deploy:
          requires:
            - check_version
            - lint_style
            - lint_types
            - test_code
            - test_docs
          filters:
            branches:
              only: master
